pipeline {
    agent {
        node {
            label 'robomart'
        }
    }

    environment {
        AWS_REGION = "us-east-1"
        AWS_CREDS = "aws-creds"
    }
    options{
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages {
        stage ('Init') {
            steps {
                script {
                    withAWS(region:"${AWS_REGION}", credentials: "${AWS_CREDS}") {
                        sh """
                            cd 20-bastion
                            terraform init
                        """
                    }
                }
            }
        }

        stage ('Plan') {
            steps {
                script {
                    withAWS(region:"${AWS_REGION}", credentials: "${AWS_CREDS}") {
                        sh """
                            cd 20-bastion
                            terraform plan
                        """
                    }
                }
            }
        }

        stage ('Deploy'){
            steps {
                script {
                    withAWS(region:"${AWS_REGION}", credentials: "${AWS_CREDS}") {
                        sh """
                            cd 20-bastion
                            terraform apply --auto-approve
                        """
                    }
                }
            }
        }
    }
    post {
        always {
            echo "Post Message after stages"
            cleanWs()
        }
        success {
            echo "Infra is success"
        }
        failure {
            echo "Infra is failure"
        }
    }
}